package game.guessword;

public class Answer {
    static final String[] level = {
            "",
            "sunflower",
            "second hand",
            "t shirt",
            "earthquake",
            "dragonfly",
            "snowflower",
            "Rooftop",
            "Seahorse",
            "Night owl",
            "Batman",
            "Snakehead fish",
            "Grapefruit",
            "Sea lion",
            "Lemongrass",
            "Spring onion",
            "Pancake",
            "Starfruit",
            "Sweet potato",
            "Breadfruit",
            "Ice-cream",
            "Goldfish",
            "Ring finger",
            "Newspaper",
            "Deadline",
            "Firefox",
            "Eyelid",
            "Redbull",
            "Car wash",
            "Rockstar",
            "Broken heart",
            "Cat fish",
            "Honeymoon",
            "Kidnap",
            "Cocktail",
            "Peacock",
            "Pineapple",
            "Fast food",
            "Popcorn",
            "French Toast",
            "Second-hand",
            "Waterfall",
            "Full moon",
            "Blackmail",
            "like",
            "love",
            "finish",
            "build",
            "drive",
            "break",
            "angry",
            "family",
            "hang",
            "laugh",
            "cat",
            "catch",
            "ride",
            "whisper",
            "erase",
            "wear",
            "nail",
            "taste",
            "star fish",
            "table tennis",
            "archery",
            "boxing",
            "rugby",
            "Fanta",
            "Sprite",
            "Redbull",
            "7-Up",
            "turkey",
            "eagle",
            "bear",
            "monkey",
            "reindeer",
            "snail",
            "mango",
            "pear"
    };
}